# Generated by Django 5.1.4 on 2024-12-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangowebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
